# Satisfactory Dedicated Server
# https://github.com/thelamescriptkiddiemax/
#-----------------------------------------------------------------------------------------------------------------------------------------------------------
# SteamCMD Base Image
FROM dockrbyter/steamcmd
#-----------------------------------------------------------------------------------------------------------------------------------------------------------
# Label
LABEL image.authors="Max"
LABEL description="Satisfactory Dedicated Server"
LABEL "other"="https://github.com/thelamescriptkiddiemax"
#-----------------------------------------------------------------------------------------------------------------------------------------------------------

# Working Directory
WORKDIR "/home/steam"

# RUNs
RUN steamcmd +login anonymous +force_install_dir /home/steam/server +app_update 1690800 +quit
RUN chown -R "steam:steam" "/home/steam/server"

# Copy
COPY startfactory.sh /home/steam/Engine.ini
COPY startfactory.sh /home/steam/startfactory.sh

#-----------------------------------------------------------------------------------------------------------------------------------------------------------

# Volume
VOLUME "/home/steam/server"

# Expose Ports: 
EXPOSE 15777/udp 15000/udp 7777/udp

#-----------------------------------------------------------------------------------------------------------------------------------------------------------

# Start Satisfactory Server
CMD [ "./startfactory.sh" ]
