# Satisfactory Dedicated Server
#
#
# https://github.com/thelamescriptkiddiemax/
#
#-----------------------------------------------------------------------------------------------------------------------------------------------------------
# SteamCMD Base Image
FROM dockrbyter/steamcmd
#-----------------------------------------------------------------------------------------------------------------------------------------------------------
# Label
LABEL image.authors="Max"
LABEL description="Satisfactory Dedicated Server"
LABEL "other"="https://github.com/thelamescriptkiddiemax"
#-----------------------------------------------------------------------------------------------------------------------------------------------------------

# RUNs
RUN steamcmd +login anonymous +force_install_dir /home/steam/server +app_update 1690800 +quit

#-----------------------------------------------------------------------------------------------------------------------------------------------------------

# Volume
VOLUME [ "/home/steam/server" ]

# Expose Ports: 
EXPOSE 15777 15000 7777

#-----------------------------------------------------------------------------------------------------------------------------------------------------------

# Start Satisfactory Server
CMD [ "./server/FactoryServer.sh" ]
