# Space Engineers - Windows Core Server
# https://github.com/thelamescriptkiddiemax/GameServer/tree/master/Docker/Windows/
#
#-----------------------------------------------------------------------------------------------------------------------------------------------------------

# SteamCMD Windows Server
FROM dockrbyter/winsteamcmd
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

#-----------------------------------------------------------------------------------------------------------------------------------------------------------
# Variables
ENV SCRP="C:\scripts" \
    CONTP="C:\content" \
    SRVBP="C:\spaceengineers" \
    WORLDP="C:\world" \
    PORTGAME="27016" \
    PORTWEB="8080"
#-----------------------------------------------------------------------------------------------------------------------------------------------------------
# Container Contsruction
RUN New-Item -Type Directory $ENV:SCRP; \
    New-Item -Type Directory $ENV:CONTP; \
    New-Item -Type Directory $ENV:WORLDP; \
    New-Item -Type Directory $ENV:SRVBP; \
    Set-Location -Path $ENV:CONTP; \
    wget https://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe -OutFile net4.exe; \
    wget https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x64.exe -OutFile vc13.exe; \
    wget https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x64.exe -OutFile vc15.exe; \
    Start-Process net4.exe -ArgumentList '/q' -Wait; \
    Start-Process vc13.exe -ArgumentList '/install', '/passive', '/norestart' -Wait; \
    Start-Process vc15.exe -ArgumentList '/install', '/passive', '/norestart' -Wait

COPY start.ps1 $SCRP/start.ps1
ADD SpaceEngineersDedicatedTestWorld.zip $CONTP
RUN Expand-Archive -LiteralPath 'C:\content\SpaceEngineersDedicatedTestWorld.zip' -DestinationPath $ENV:WORLDP
#-----------------------------------------------------------------------------------------------------------------------------------------------------------
# Persistent Data
VOLUME $WORLDP
VOLUME $SRVBP

# Port Exposing
EXPOSE $PORTGAME/udp $PORTWEB/tcp

# Start Server
WORKDIR $SCRP
ENTRYPOINT  [ "PowerShell.exe", "-NoExit", ".\\start.ps1" ]
