# Kerbal Space Program DMP Dedicated Server
#
# https://github.com/thelamescriptkiddiemax/
#-----------------------------------------------------------------------------------------------------------------------------------------------------------
# Base Image 
FROM mono
#-----------------------------------------------------------------------------------------------------------------------------------------------------------
# Label
LABEL image.authors="Max"
LABEL description="KSP DMP Dedicated Server"
LABEL "other"="https://github.com/thelamescriptkiddiemax"
#-----------------------------------------------------------------------------------------------------------------------------------------------------------

# Environment Variables
ENV PORTGAME=6702

#-----------------------------------------------------------------------------------------------------------------------------------------------------------

# Download Server Files
RUN mkdir -p /ksp/setup
ADD https://d-mp.org/builds/release/v0.3.8.0/DMPServer.zip /ksp/setup/

# Setup Server
WORKDIR /ksp/setup
RUN apt update -y && \
    apt upgrade -y && \
    apt install zip -y && \
    unzip *.zip -d /ksp/setup && \
    mv -v /ksp/setup/DMPServer/* /ksp

WORKDIR /ksp    
RUN rm -r setup/ && \
    chmod +x DMPServer.exe

#-----------------------------------------------------------------------------------------------------------------------------------------------------------

# Persistent Data
VOLUME /ksp/Config
VOLUME /ksp/Universe

#-----------------------------------------------------------------------------------------------------------------------------------------------------------

# Expose Ports
EXPOSE $PORTGAME/tcp

#-----------------------------------------------------------------------------------------------------------------------------------------------------------

# Start Server
ENTRYPOINT ["mono", "./DMPServer.exe" ]