# ARK: Survival Evolved Dedicated Server
#
# https://github.com/thelamescriptkiddiemax/
#-----------------------------------------------------------------------------------------------------------------------------------------------------------
# SteamCMD Base Image
FROM dockrbyter/steamcmd
#-----------------------------------------------------------------------------------------------------------------------------------------------------------
# Label
LABEL image.authors="Max"
LABEL description="ARK Survival Evolved Dedicated Server"
LABEL "other"="https://github.com/thelamescriptkiddiemax"
#-----------------------------------------------------------------------------------------------------------------------------------------------------------

# Environment Variables
ENV GAMEID=376030 \
    SERVERNAME=dockrbyter \
    DIRCLUSTER=/home/steam/arkdata \
    MAP=TheIsland \
    MAXPLAYERS=16 \
    ADMINPW=welovemax \
    CLUSTERID=dockrbyter \
    MULTIHOMEIP=0.0.0.0 \
    PORTGAME=7777 \
    PORTRAW=7778 \
    PORTQUERY=27015 \
    PORTRCON=27020 \
    RCONON=True
    USER=steam

#-----------------------------------------------------------------------------------------------------------------------------------------------------------

# Create Directories
RUN mkdir -p /home/steam/arkdata

# Copy Start Script
COPY startark.sh /home/steam/startark.sh

#-----------------------------------------------------------------------------------------------------------------------------------------------------------

# Persistent Data
VOLUME /home/steam/server
VOLUME /home/steam/arkdata
VOLUME /.steam

#-----------------------------------------------------------------------------------------------------------------------------------------------------------

# Expose Ports
EXPOSE $PORTGAME/udp $PORTRAW/udp $PORTQUERY/udp $PORTRCON/tcp 

#-----------------------------------------------------------------------------------------------------------------------------------------------------------

# Start Ark Server
CMD [ "/home/steam/startark.sh" ]
