# ARK: Survival Evolved Dedicated Server
#
# https://github.com/thelamescriptkiddiemax/
#-----------------------------------------------------------------------------------------------------------------------------------------------------------
# SteamCMD Base Image
FROM dockrbyter/steamcmd
#-----------------------------------------------------------------------------------------------------------------------------------------------------------
# Label
LABEL image.authors="Max"
LABEL description="ARK Survival Evolved Dedicated Server"
LABEL "other"="https://github.com/thelamescriptkiddiemax"
#-----------------------------------------------------------------------------------------------------------------------------------------------------------

# Build Arguments
ARG DIRDATA=/home/steam/arkdata

# Environment Variables
ENV GAMEID=376030 \
    DIRSAVE=${DIRDATA}/savegames/$SERVERNAME \
    DIRCLUSTER=${DIRDATA}/cluster \
    SERVERNAME=dockrbyter \
    MAP=TheIsland \
    MAXPLAYERS=16 \
    SERVERPW=welovemax \
    ADMINPW=welovemax \
    CLUSTERID=dockrbyter \
    MULTIHOMEIP=0.0.0.0 \
    PORTGAME=7777 \
    PORTRAW=7778 \
    PORTQUERY=27015 \
    PORTRCON=27020 \
    RCONON=True

#-----------------------------------------------------------------------------------------------------------------------------------------------------------

# RUNs
RUN mkdir -p $DIRCLUSTER

# Copy Start Script
COPY startark.sh /home/steam/startark.sh

#-----------------------------------------------------------------------------------------------------------------------------------------------------------

# Persistent Data
VOLUME /home/steam/server
VOLUME ${DIRDATA}

#-----------------------------------------------------------------------------------------------------------------------------------------------------------

# Expose Ports
EXPOSE $PORTGAME/udp $PORTRAW/udp $PORTQUERY/udp $PORTRCON/tcp 

#-----------------------------------------------------------------------------------------------------------------------------------------------------------

# Start Ark Server
CMD [ "./startark.sh" ]